# Intent Rules Configuration
# 意圖規則配置 - 確定性問題用規則，複雜性問題用AI

# 取消課程意圖
cancel_course:
  keywords: ['取消', '刪除', '移除', '不要', '不上', '停止', '撤銷']
  priority: 10
  exclusions: ['新增', '安排', '預約', '報名', '登記']
  examples:
    - "取消數學課"
    - "刪除英文課"
    - "不要上物理課"

# 新增課程意圖  
record_course:
  keywords: ['新增', '安排', '預約', '上課', '學習', '報名', '登記', '加入', '上', '課', '有', '要', '教學', '教', '訓練', '培訓', '輔導', '指導']
  priority: 6  # 提高優先級
  exclusions: ['取消', '刪除', '不要', '停止', '移除', '查詢', '看', '顯示', '修改', '更改', '調整', '提醒', '通知', '課表', '時間表', '什麼課']
  patterns: ['.*課$', '.*課程$', '.*班$', '.*教學$', '.*教$', '.*訓練$', '.*培訓$', '.*輔導$', '.*指導$', '.*時.*課', '.*[點時].*課', '.*[點時].*教學', '.*[點時].*教', '今天.*課', '今天.*教學', '明天.*課', '明天.*教學', '下週.*課', '下週.*教學']
  examples:
    - "明天2:30英文課"
    - "安排數學課"
    - "我要上物理課"
    - "今天下午有數學課"
    - "明天晚上十點半法語課"

# 查詢課表意圖
query_schedule:
  keywords: ['查詢', '看', '顯示', '課表', '時間表', '什麼課', '有什麼', '安排']
  priority: 9  # 提高優先級
  exclusions: ['新增', '取消', '刪除', '修改', '更改']
  examples:
    - "查詢我的課表"
    - "看看今天有什麼課"
    - "顯示下周的安排"

# 修改課程意圖
modify_course:
  keywords: ['修改', '更改', '調整', '改變', '編輯', '更新', '改成', '改到', '換成', '換到', '變更']
  priority: 12  # 提高優先級，高於 record_course
  exclusions: ['新增', '取消', '刪除', '查詢', '看', '顯示', '安排']
  patterns: ['.*改成.*', '.*改到.*', '.*換成.*', '.*換到.*', '.*課.*改.*', '修改.*課.*', '調整.*課.*', '更改.*課.*']
  examples:
    - "修改數學課時間"
    - "調整英文課到下午"
    - "更改物理課老師"
    - "直排輪課改成明天上午10點"
    - "數學課改到下午3點"
    - "英文課換成週三"

# 設定提醒意圖
set_reminder:
  keywords: ['提醒', '通知', '叫我', '記得', 'remind']
  priority: 7  # 提高優先級
  exclusions: ['取消', '刪除', '停止', '新增', '修改', '查詢']
  examples:
    - "數學課前10分鐘提醒我"
    - "英文課開始時通知我"
    - "記得叫我上物理課"

# 糾錯意圖 - 基於上下文的修改指令
correction_intent:
  keywords: ['不對', '錯了', '錯誤', '不是', '改正', '糾正', '弄錯', '有誤', '不正確']
  priority: 15  # 最高優先級，優先於其他修改意圖
  exclusions: []  # 不排除任何詞彙，因為糾錯可能包含各種表達
  patterns: ['^不對.*', '^錯了.*', '^不是.*', '不對.*改成.*', '錯了.*改成.*', '不是.*應該.*', '弄錯.*', '有誤.*']
  requires_context: true  # 標記此意圖需要會話上下文
  examples:
    - "不對 改成下午四點30"
    - "錯了 應該是明天上午"
    - "不是這個時間 改成週三"
    - "弄錯了 改成英文課"
    - "不對的 改成下午2點"

# 清空課表意圖 - 高風險操作，需要二步確認
clear_schedule:
  keywords: ['清空', '全部刪除', '刪除所有', '清除所有', '清理', '全清', '重置課表', '清空課表', '確認清空', '確認']
  priority: 11  # 最高優先級，避免誤判
  exclusions: ['新增', '安排', '預約', '修改', '查詢', '看', '顯示', '單個', '一個']
  patterns: ['清空.*課表', '刪除.*所有.*課', '清除.*全部.*課', '全部.*清空', '^確認清空$', '^確認$']
  examples:
    - "清空我的課表"
    - "刪除所有課程"
    - "清除全部課程安排"
    - "重置我的課表"
    - "確認清空"
    - "確認"