# Intent Rules Configuration
# 意圖規則配置 - 確定性問題用規則，複雜性問題用AI

# 取消課程意圖
cancel_course:
  keywords: ['取消', '刪除', '移除', '不要', '不上', '撤銷']
  priority: 10
  exclusions: ['新增', '安排', '預約', '報名', '登記', '每週', '每周', '每天', '每月', '重複', '定期']
  examples:
    - "取消數學課"
    - "刪除英文課"
    - "不要上物理課"

# 停止重複課程意圖
stop_recurring_course:
  keywords: ['停止', '結束', '暫停', '中止', '終止', '取消', '不要']
  priority: 14  # 提高優先級，確保在 query_schedule 之前
  required_keywords: ['每週', '每周', '每天', '每月', '重複', '定期', '固定', '循環', '週期性']
  exclusions: ['新增', '預約', '報名', '登記', '修改', '更改', '調整', '查詢', '看', '顯示']  # 移除 "安排" 從排除詞
  patterns: ['停止.*每週.*課', '停止.*每周.*課', '結束.*重複.*課', '暫停.*定期.*課', '.*重複.*課.*停止.*', '.*每週.*課.*結束.*', '.*每周.*課.*結束.*', '取消.*每週.*課', '取消.*每周.*課', '取消.*重複.*課', '不要.*每週.*課', '不要.*每周.*課', '不要.*重複.*課', '停止.*安排', '不要.*安排.*重複', '不要.*重複.*安排']
  examples:
    - "停止數學課每週安排"
    - "結束重複瑜伽課"
    - "暫停定期游泳課"
    - "不要再重複安排英文課"
    - "取消每週數學課"
    - "停止重複英文課"

# 新增課程意圖  
record_course:
  keywords: ['新增', '安排', '預約', '上課', '學習', '報名', '登記', '加入', '上', '課', '有', '要', '教學', '教', '訓練', '培訓', '輔導', '指導']
  priority: 6  # 提高優先級
  exclusions: ['取消', '刪除', '不要', '停止', '移除', '查詢', '看', '顯示', '修改', '更改', '調整', '提醒', '通知', '課表', '時間表', '什麼課', '每週', '每周', '每天', '每月', '重複', '定期']
  patterns: ['.*課$', '.*課程$', '.*班$', '.*教學$', '.*教$', '.*訓練$', '.*培訓$', '.*輔導$', '.*指導$', '.*時.*課', '.*[點時].*課', '.*[點時].*教學', '.*[點時].*教', '今天.*課', '今天.*教學', '明天.*課', '明天.*教學', '下週.*課', '下週.*教學']
  examples:
    - "明天2:30英文課"
    - "安排數學課"
    - "我要上物理課"
    - "今天下午有數學課"
    - "明天晚上十點半法語課"

# 創建重複課程意圖
create_recurring_course:
  keywords: ['每週', '每周', '每天', '每月', '重複', '定期', '固定', '循環', '週期性']
  priority: 8  # 高優先級，避免被 record_course 覆蓋
  exclusions: ['取消', '刪除', '停止', '移除', '查詢', '看', '顯示', '修改', '更改', '調整']
  patterns: ['每週.*課', '每周.*課', '每天.*課', '每月.*課', '重複.*課', '定期.*課', '.*課.*每週', '.*課.*每周', '.*課.*每天', '.*課.*每月', '固定.*課', '週期性.*課']
  examples:
    - "數學課每週一下午2點"
    - "英文課每週三晚上7點"
    - "每天早上8點晨練"
    - "定期瑜伽課每週五"
    - "重複安排游泳課"

# 查詢課表意圖
query_schedule:
  keywords: ['查詢', '看', '顯示', '課表', '時間表', '什麼課', '有什麼', '安排']
  priority: 9  # 提高優先級
  exclusions: ['新增', '取消', '刪除', '修改', '更改']
  examples:
    - "查詢我的課表"
    - "看看今天有什麼課"
    - "顯示下周的安排"

# 修改課程意圖
modify_course:
  keywords: ['修改', '更改', '調整', '改變', '編輯', '更新', '改成', '改到', '換成', '換到', '變更']
  priority: 12  # 提高優先級，高於 record_course
  exclusions: ['新增', '取消', '刪除', '查詢', '看', '顯示', '安排', '每週', '每周', '每天', '每月', '重複', '定期', '停止']
  patterns: ['.*改成.*', '.*改到.*', '.*換成.*', '.*換到.*', '.*課.*改.*', '修改.*課.*', '調整.*課.*', '更改.*課.*']
  examples:
    - "修改數學課時間"
    - "調整英文課到下午"
    - "更改物理課老師"
    - "直排輪課改成明天上午10點"
    - "數學課改到下午3點"
    - "英文課換成週三"

# 修改重複課程意圖
modify_recurring_course:
  keywords: ['修改', '更改', '調整', '改變', '編輯', '更新', '改成', '改到', '換成', '換到', '變更']
  priority: 13  # 比 modify_course 稍高
  required_keywords: ['每週', '每周', '每天', '每月', '重複', '定期', '固定', '循環', '週期性']  # 需要包含重複相關詞彙
  exclusions: ['新增', '取消', '刪除', '查詢', '看', '顯示', '安排', '停止']
  patterns: ['修改.*每週.*課', '調整.*重複.*課', '更改.*定期.*課', '.*重複.*課.*改.*', '.*每週.*課.*調整.*']
  examples:
    - "修改數學課每週時間"
    - "調整重複瑜伽課到下午"
    - "更改定期游泳課頻率"
    - "數學課的重複安排改成每週二"

# 設定提醒意圖
set_reminder:
  keywords: ['提醒', '通知', '叫我', '記得', 'remind']
  priority: 7  # 提高優先級
  exclusions: ['取消', '刪除', '停止', '新增', '修改', '查詢']
  examples:
    - "數學課前10分鐘提醒我"
    - "英文課開始時通知我"
    - "記得叫我上物理課"

# 糾錯意圖 - 基於上下文的修改指令
correction_intent:
  keywords: ['不對', '錯了', '錯誤', '不是', '改正', '糾正', '弄錯', '有誤', '不正確']
  priority: 15  # 最高優先級，優先於其他修改意圖
  exclusions: []  # 不排除任何詞彙，因為糾錯可能包含各種表達
  patterns: ['^不對.*', '^錯了.*', '^不是.*', '不對.*改成.*', '錯了.*改成.*', '不是.*應該.*', '弄錯.*', '有誤.*']
  requires_context: true  # 標記此意圖需要會話上下文
  examples:
    - "不對 改成下午四點30"
    - "錯了 應該是明天上午"
    - "不是這個時間 改成週三"
    - "弄錯了 改成英文課"
    - "不對的 改成下午2點"

# 清空課表意圖 - 高風險操作，需要二步確認
clear_schedule:
  keywords: ['清空', '全部刪除', '刪除所有', '清除所有', '清理', '全清', '重置課表', '清空課表', '確認清空', '確認']
  priority: 11  # 最高優先級，避免誤判
  exclusions: ['新增', '安排', '預約', '修改', '查詢', '看', '顯示', '單個', '一個']
  patterns: ['清空.*課表', '刪除.*所有.*課', '清除.*全部.*課', '全部.*清空', '^確認清空$', '^確認$']
  examples:
    - "清空我的課表"
    - "刪除所有課程"
    - "清除全部課程安排"
    - "重置我的課表"
    - "確認清空"
    - "確認"