# Intent Rules Configuration
# 意圖規則配置 - 確定性問題用規則，複雜性問題用AI

# 取消課程意圖
cancel_course:
  keywords: ['取消', '刪除', '移除', '不要', '不上', '停止', '撤銷']
  priority: 10
  exclusions: ['新增', '安排', '預約', '報名', '登記']
  examples:
    - "取消數學課"
    - "刪除英文課"
    - "不要上物理課"

# 新增課程意圖  
record_course:
  keywords: ['新增', '安排', '預約', '上課', '學習', '報名', '登記', '加入', '上', '課', '有', '要']
  priority: 6  # 提高優先級
  exclusions: ['取消', '刪除', '不要', '停止', '移除', '查詢', '看', '顯示', '修改', '更改', '調整', '提醒', '通知', '課表', '時間表', '什麼課']
  patterns: ['.*課$', '.*課程$', '.*班$', '.*時.*課', '.*[點時].*課', '今天.*課', '明天.*課', '下週.*課']
  examples:
    - "明天2:30英文課"
    - "安排數學課"
    - "我要上物理課"
    - "今天下午有數學課"
    - "明天晚上十點半法語課"

# 查詢課表意圖
query_schedule:
  keywords: ['查詢', '看', '顯示', '課表', '時間表', '什麼課', '有什麼', '安排']
  priority: 9  # 提高優先級
  exclusions: ['新增', '取消', '刪除', '修改', '更改']
  examples:
    - "查詢我的課表"
    - "看看今天有什麼課"
    - "顯示下周的安排"

# 修改課程意圖
modify_course:
  keywords: ['修改', '更改', '調整', '改變', '編輯', '更新']
  priority: 8
  exclusions: ['新增', '取消', '刪除', '查詢', '看', '顯示']
  examples:
    - "修改數學課時間"
    - "調整英文課到下午"
    - "更改物理課老師"

# 設定提醒意圖
set_reminder:
  keywords: ['提醒', '通知', '叫我', '記得', 'remind']
  priority: 7  # 提高優先級
  exclusions: ['取消', '刪除', '停止', '新增', '修改', '查詢']
  examples:
    - "數學課前10分鐘提醒我"
    - "英文課開始時通知我"
    - "記得叫我上物理課"