# Intent Rules Configuration
# 意圖規則配置 - 確定性問題用規則，複雜性問題用AI

# ===============================
# 操作性意圖 (Quick Reply & Context Actions)
# ===============================

# 確認操作意圖 - 用於 Quick Reply 按鈕
confirm_action:
  keywords: ['確認', '好', '對', '是的', '沒錯', '正確', 'OK', 'ok', '好的', '是', '可以']
  priority: 20  # 最高優先級
  exclusions: []  # 不排除任何詞，因為確認動作很簡單
  patterns: ['^確認$', '^好$', '^對$', '^是的$', '^沒錯$', '^正確$', '^OK$', '^ok$', '^好的$', '^是$', '^可以$']
  requires_context: true  # 標記此意圖需要會話上下文
  examples:
    - "確認"
    - "好"
    - "對"
    - "是的"
    - "沒錯"

# 修改操作意圖 - 用於 Quick Reply 按鈕
modify_action:
  keywords: ['修改', '更改', '調整', '改', '變更', '不對']
  priority: 19  # 次高優先級
  exclusions: ['新增', '刪除', '查詢', '課程', '時間', '學生']  # 排除具體操作詞
  patterns: ['^修改$', '^更改$', '^調整$', '^改$', '^變更$', '^不對$']
  requires_context: true  # 標記此意圖需要會話上下文
  examples:
    - "修改"
    - "更改"
    - "調整"
    - "改"
    - "不對"

# 取消操作意圖 - 用於 Quick Reply 按鈕
cancel_action:
  keywords: ['取消操作', '取消', '算了', '不要', '放棄', '重新開始', '重來']
  priority: 18  # 高優先級
  exclusions: ['課程', '課', '學生', '時間']  # 排除具體操作對象
  patterns: ['^取消操作$', '^取消$', '^算了$', '^不要$', '^放棄$', '^重新開始$', '^重來$']
  requires_context: true  # 標記此意圖需要會話上下文
  examples:
    - "取消操作"
    - "取消"
    - "算了"
    - "不要"
    - "放棄"

# 重新輸入意圖 - 用於重新開始對話流程
restart_input:
  keywords: ['重新輸入', '重新說', '重新來', '重來', '重新開始', '再說一次']
  priority: 17  # 高優先級
  exclusions: []
  patterns: ['^重新輸入$', '^重新說$', '^重新來$', '^重來$', '^重新開始$', '^再說一次$']
  requires_context: true
  examples:
    - "重新輸入"
    - "重新說"
    - "重來"
    - "重新開始"

# ===============================
# 核心功能意圖 (Core Functions)
# ===============================

# 取消課程意圖
cancel_course:
  keywords: ['取消', '刪除', '刪掉', '移除', '不要', '不上', '撤銷']
  priority: 10
  exclusions: ['新增', '安排', '預約', '報名', '登記', '每週', '每周', '每天', '每月', '重複', '定期']
  examples:
    - "取消數學課"
    - "刪除英文課"
    - "刪掉Lumi的英文課"
    - "不要上物理課"

# 停止重複課程意圖
stop_recurring_course:
  keywords: ['停止', '結束', '暫停', '中止', '終止', '取消', '不要']
  priority: 14  # 提高優先級，確保在 query_schedule 之前
  required_keywords: ['每週', '每周', '每天', '每月', '重複', '定期', '固定', '循環', '週期性']
  exclusions: ['新增', '預約', '報名', '登記', '修改', '更改', '調整', '查詢', '看', '顯示']  # 移除 "安排" 從排除詞
  patterns: ['停止.*每週.*課', '停止.*每周.*課', '結束.*重複.*課', '暫停.*定期.*課', '.*重複.*課.*停止.*', '.*每週.*課.*結束.*', '.*每周.*課.*結束.*', '取消.*每週.*課', '取消.*每周.*課', '取消.*重複.*課', '不要.*每週.*課', '不要.*每周.*課', '不要.*重複.*課', '停止.*安排', '不要.*安排.*重複', '不要.*重複.*安排']
  examples:
    - "停止數學課每週安排"
    - "結束重複瑜伽課"
    - "暫停定期游泳課"
    - "不要再重複安排英文課"
    - "取消每週數學課"
    - "停止重複英文課"

# 新增課程意圖  
add_course:
  keywords: ['新增', '安排', '預約', '上課', '學習', '報名', '登記', '加入', '上', '課', '有', '要']
  # 移除過嚴格的 required_keywords，允許自然語句如 "學生+時間+課程" 格式
  priority: 10  # 一般課程記錄的標準優先級
  exclusions: ['取消', '刪除', '刪掉', '不要', '停止', '移除', '查詢', '看', '顯示', '修改', '更改', '調整', '提醒', '通知', '課表', '時間表', '什麼課', '有什麼', '有啥', '啥課', '教了', '學了', '練習了', '內容', '表現', '老師說', '很好', '成功', '厲害', '棒']  # 排除記錄內容語句
  patterns: ['.*課$', '.*課程$', '.*班$', '.*教學$', '.*教$', '.*訓練$', '.*培訓$', '.*輔導$', '.*指導$', '.*時.*課', '.*[點時].*課', '.*[點時].*教學', '.*[點時].*教', '今天.*[點時].*課', '明天.*[點時].*課', '下週.*[點時].*課', '.*[點時]半.*課', '.*早上.*課', '.*下午.*課', '.*晚上.*課', '.*中午.*課']
  examples:
    - "明天2:30英文課"
    - "安排數學課"
    - "我要上物理課"
    - "今天下午有數學課"
    - "明天晚上十點半法語課"
    - "小明明天早上十點半足球課"

# 創建重複課程意圖
create_recurring_course:
  keywords: ['每週', '每周', '每天', '每日', '每月', '重複', '定期', '固定', '循環', '週期性', '週一', '週二', '週三', '週四', '週五', '週六', '週日', '周一', '周二', '周三', '周四', '周五', '周六', '周日']
  priority: 12  # 🎯 最高優先級，確保重複課程優先被識別
  exclusions: ['取消', '刪除', '停止', '移除', '查詢', '看', '顯示', '修改', '更改', '調整']
  patterns: ['每週.*課', '每周.*課', '每天.*課', '每日.*課', '每月.*課', '重複.*課', '定期.*課', '.*課.*每週', '.*課.*每周', '.*課.*每天', '.*課.*每日', '.*課.*每月', '固定.*課', '週期性.*課', '週[一二三四五六日].*課', '周[一二三四五六日].*課', '.*課.*週[一二三四五六日]', '.*課.*周[一二三四五六日]', '每週[一二三四五六日].*', '每周[一二三四五六日].*']  # 🎯 新增更多模式
  required_keywords: ['每週', '每周', '每天', '每日', '每月']  # 🎯 至少包含一個重複關鍵詞
  examples:
    - "數學課每週一下午2點"
    - "英文課每週三晚上7點"
    - "每天早上8點晨練"
    - "定期瑜伽課每週五"
    - "重複安排游泳課"
    - "LUMI每週三下午三點有科學實驗課"  # 🎯 新增測試案例

# 查詢課表意圖
query_schedule:
  keywords: ['查詢', '看', '看看', '顯示', '課表', '時間表', '什麼課', '有什麼', '安排', '行程', '課程', '有啥', '啥課']
  priority: 9  # 提高優先級
  exclusions: ['新增', '取消', '刪除', '修改', '更改', '每週', '每周', '每天', '每月', '點', '點半', '時', '時半']  # 新增時間相關排除詞
  patterns: ['.*課表.*', '.*時間表.*', '.*什麼課.*', '.*有什麼.*課', '.*有.*啥.*課', '.*昨天.*有.*課', '.*行程.*', '今天.*有.*課', '明天.*有.*課', '這週.*有.*課', '下週.*有.*課', '本週.*有.*課', '這周.*有.*課', '下周.*有.*課', '本周.*有.*課', '.*有.*什麼.*課', '查詢.*今天', '查詢.*明天', '看.*今天', '看.*明天', '顯示.*今天', '顯示.*明天']  # 修改模式，要求更明確的查詢意圖
  examples:
    - "查詢我的課表"
    - "看看今天有什麼課"
    - "顯示下周的安排"
    - "今天有課嗎"
    - "我明天的行程"
    - "明天有什麼課"
    - "查詢明天課表"

# 修改課程意圖
modify_course:
  keywords: ['修改', '更改', '調整', '改變', '編輯', '更新', '改成', '改到', '換成', '換到', '變更']
  priority: 12  # 提高優先級，高於 add_course
  exclusions: ['新增', '取消', '刪除', '查詢', '看', '顯示', '安排', '每週', '每周', '每天', '每月', '重複', '定期', '停止']
  patterns: ['.*改成.*', '.*改到.*', '.*換成.*', '.*換到.*', '.*課.*改.*', '修改.*課.*', '調整.*課.*', '更改.*課.*']
  examples:
    - "修改數學課時間"
    - "調整英文課到下午"
    - "更改物理課老師"
    - "直排輪課改成明天上午10點"
    - "數學課改到下午3點"
    - "英文課換成週三"

# 修改重複課程意圖
modify_recurring_course:
  keywords: ['修改', '更改', '調整', '改變', '編輯', '更新', '改成', '改到', '換成', '換到', '變更']
  priority: 13  # 比 modify_course 稍高
  required_keywords: ['每週', '每周', '每天', '每月', '重複', '定期', '固定', '循環', '週期性']  # 需要包含重複相關詞彙
  exclusions: ['新增', '取消', '刪除', '查詢', '看', '顯示', '安排', '停止']
  patterns: ['修改.*每週.*課', '調整.*重複.*課', '更改.*定期.*課', '.*重複.*課.*改.*', '.*每週.*課.*調整.*']
  examples:
    - "修改數學課每週時間"
    - "調整重複瑜伽課到下午"
    - "更改定期游泳課頻率"
    - "數學課的重複安排改成每週二"

# 設定提醒意圖
set_reminder:
  keywords: ['提醒', '通知', '叫我', '記得', 'remind']
  priority: 7  # 提高優先級
  exclusions: ['取消', '刪除', '停止', '新增', '修改', '查詢']
  examples:
    - "數學課前10分鐘提醒我"
    - "英文課開始時通知我"
    - "記得叫我上物理課"

# 糾錯意圖 - 基於上下文的修改指令
correction_intent:
  keywords: ['不對', '錯了', '錯誤', '不是', '改正', '糾正', '弄錯', '有誤', '不正確']
  priority: 15  # 最高優先級，優先於其他修改意圖
  exclusions: []  # 不排除任何詞彙，因為糾錯可能包含各種表達
  patterns: ['^不對.*', '^錯了.*', '^不是.*', '不對.*改成.*', '錯了.*改成.*', '不是.*應該.*', '弄錯.*', '有誤.*']
  requires_context: true  # 標記此意圖需要會話上下文
  examples:
    - "不對 改成下午四點30"
    - "錯了 應該是明天上午"
    - "不是這個時間 改成週三"
    - "弄錯了 改成英文課"
    - "不對的 改成下午2點"

# 清空課表意圖 - 高風險操作，需要二步確認
clear_schedule:
  keywords: ['清空', '全部刪除', '刪除所有', '清除所有', '清理', '全清', '重置課表', '清空課表', '確認清空']
  priority: 11  # 最高優先級，避免誤判
  exclusions: ['新增', '安排', '預約', '修改', '查詢', '看', '顯示', '單個', '一個']
  patterns: ['清空.*課表', '刪除.*所有.*課', '清除.*全部.*課', '全部.*清空', '^確認清空$']
  # 移除通用的 '確認' 關鍵詞和 '^確認$' 模式，避免與快捷回覆衝突
  examples:
    - "清空我的課表"
    - "刪除所有課程"
    - "清除全部課程安排"
    - "重置我的課表"
    - "確認清空"
    - "確認"

# ===============================
# 課程內容管理意圖 (Course Content)
# ===============================

# 記錄課程內容意圖
add_course_content:
  keywords: ['課程', '上課內容', '課堂內容', '學習內容', '課程記錄', '筆記', '重點', '學到', '教了', '講解', '說明', '內容', '表現', '反饋', '評價', '老師說', '很好', '成功', '不錯', '棒', '厲害', '造出', '做出', '完成']
  priority: 13  # 🎯 最高優先級，確保課程內容記錄優先被識別
  exclusions: ['作業', '功課', '練習', '照片', '圖片', '查詢', '看', '顯示', '修改', '刪除', '新增', '安排', '預約']
  patterns: [
    # 今天的課程內容記錄
    '今天.*課.*學了.*', 
    '今天.*課.*教了.*', 
    '今天.*學到.*', 
    '今天.*表現.*', 
    '今天.*反饋.*', 
    '今天.*評價.*',
    '今天的.*表現.*',
    '今天的.*很好.*',
    '今天的.*不錯.*',
    '今天.*課.*表現.*',
    '老師說.*今天.*',
    # 🎯 新增：昨天的課程內容記錄
    '昨天.*課.*學了.*',
    '昨天.*課.*教了.*', 
    '昨天.*學到.*',
    '昨天.*表現.*',
    '昨天.*反饋.*',
    '昨天.*評價.*',
    '昨天的.*表現.*',
    '昨天的.*很好.*',
    '昨天的.*不錯.*',
    '昨天.*課.*表現.*',
    '昨天的.*課.*老師說.*',
    '昨天的.*課.*成功.*',
    '昨天的.*課.*造出.*',
    '老師說.*昨天.*',
    # 🎯 新增：前天等其他過去時間
    '前天.*課.*',
    '上週.*課.*',
    '上個月.*課.*',
    # 通用模式
    '課程.*內容.*', 
    '上課.*筆記', 
    '學習.*重點', 
    '課堂.*記錄', 
    '老師.*講解.*', 
    '課程.*說明.*',
    '.*課.*老師說.*表現.*',
    '.*課.*老師說.*很好.*',
    '.*課.*老師說.*成功.*'
  ]
  examples:
    - "今天數學課教了加法運算"
    - "記錄今天英文課的內容"
    - "老師說小明今天數學課表現很好"
    - "昨天的科學實驗課老師說他表現很好成功造出來火箭"
    - "昨天數學課學了分數"
    - "前天的英文課表現不錯"
    - "上週物理課學習光的反射"
    - "老師反饋昨天科學實驗很成功"

# 記錄作業意圖
add_homework:
  keywords: ['作業', '功課', '練習', '習題', '作業本', '練習題', '家庭作業', '回家作業', '功課單', '需要完成', '要做']
  priority: 11
  exclusions: ['完成了', '做完了', '已完成', '照片', '圖片', '查詢', '看', '顯示', '修改', '刪除']
  patterns: ['.*作業.*', '.*功課.*', '.*練習.*', '今天.*要做.*', '回家.*要.*', '需要完成.*', '老師交代.*', '功課單.*', '習題.*']
  examples:
    - "今天數學作業是第10頁"
    - "英文功課要背單字" 
    - "回家要做物理練習題"
    - "老師交代完成習作第3章"
    - "需要完成數學練習本"

# 上傳課堂照片意圖
upload_class_photo:
  keywords: ['照片', '圖片', '拍照', '課堂照片', '板書', '黑板', '白板', '上課照片', '教材', '課本', '筆記照片']
  priority: 11
  exclusions: ['作業', '功課', '內容', '查詢', '看', '顯示', '修改', '刪除']
  patterns: ['.*照片.*', '.*圖片.*', '課堂.*拍.*', '板書.*', '黑板.*', '白板.*', '教材.*照片', '課本.*照片', '筆記.*照片']
  examples:
    - "上傳今天的課堂照片"
    - "分享數學課板書照片"
    - "課本第5頁的圖片"
    - "老師寫在黑板上的內容"
    - "拍了課堂筆記照片"

# 查詢課程內容意圖
query_course_content:
  keywords: ['學了什麼', '教了什麼', '內容是什麼', '課程內容', '怎麼樣', '如何', '表現如何', '上得怎麼樣', '學得怎麼樣']
  required_keywords: ['課', '學', '教', '內容', '怎麼樣', '如何', '表現']  # 必須包含課程相關詞
  priority: 14  # 🎯 提高優先級，優先識別查詢意圖
  exclusions: ['新增', '記錄', '上傳', '拍照', '修改', '更改', '刪除', '老師說', '天氣', '心情', '狀況', '時間', '地點']  # 排除無關查詢
  patterns: [
    # 🎯 新增：詢問語氣模式
    '.*昨天.*課.*怎麼樣.*',
    '.*昨天.*課.*如何.*',
    '.*昨天.*上得怎麼樣.*',
    '.*昨天.*學得怎麼樣.*',
    '.*前天.*課.*怎麼樣.*',
    '.*上週.*課.*怎麼樣.*',
    '.*課.*上得怎麼樣.*',
    '.*課.*學得怎麼樣.*',
    '.*怎麼樣.*',
    '.*如何.*',
    '.*表現如何.*',
    '.*狀況如何.*',
    '.*的.*課.*評價.*',
    # 原有模式
    '查看.*課程內容', 
    '查詢.*學習記錄', 
    '看看.*作業', 
    '顯示.*課堂記錄', 
    '.*學習狀況', 
    '.*上課記錄', 
    '.*的內容', 
    '.*學了什麼'
  ]
  examples:
    - "查看數學課的內容記錄"
    - "看看今天學了什麼"
    - "顯示英文課的學習記錄"
    - "查詢小明的作業狀況"
    - "看看課堂記錄"
    - "LUMI昨天的科學實驗上得怎麼樣"  # 🎯 新增範例
    - "昨天數學課怎麼樣"
    - "小明今天表現如何"
    - "英文課學得怎麼樣"

# 修改課程內容意圖
modify_course_content:
  keywords: ['修改', '更改', '調整', '編輯', '更新', '改正', '修正']
  priority: 10
  required_keywords: ['內容', '記錄', '作業', '照片', '筆記']
  exclusions: ['新增', '刪除', '查詢', '上傳']
  patterns: ['修改.*內容', '更改.*記錄', '調整.*作業', '編輯.*筆記', '修正.*內容']
  examples:
    - "修改今天的課程內容記錄"
    - "更改作業描述"
    - "調整學習筆記"
    - "編輯課堂記錄"